environment:

  matrix:
    - PYTHON: "C:\\Python35"
      JAVA_HOME: "C:\\Program Files (x86)\\Java\\jdk1.8.0"

    - PYTHON: "C:\\Python35-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
    - PYTHON: "C:\\Python36-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

    - PYTHON: "C:\\Python36-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk9"
    - PYTHON: "C:\\Python36-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk10"
    - PYTHON: "C:\\Python36-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python37-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
    - PYTHON: "C:\\Python37-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk12"
    - PYTHON: "C:\\Python38-x64"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk11"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
